import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, any>) => string;
}

const translations = {
  zh: {
    // App Name
    'app.name': '班级萌宠园',
    'app.slogan': '通过完成任务，养育你的专属宠物',
    'app.footer': '班级萌宠园 · 让学习更有趣',
    'app.description': '清新活力配色 · 苹果设计美学',

    // Login Page
    'login.title': '登录',
    'login.register': '注册',
    'login.username': '用户名',
    'login.username.placeholder': '请输入用户名',
    'login.email': '邮箱',
    'login.email.placeholder': '请输入邮箱地址',
    'login.password': '密码',
    'login.password.placeholder': '请输入密码',
    'login.confirmPassword': '确认密码',
    'login.confirmPassword.placeholder': '请再次输入密码',
    'login.forgotPassword': '忘记密码？',
    'login.submit': '登录',
    'register.submit': '注册',
    'register.terms': '注册即表示同意',
    'register.termsOfService': '服务条款',
    'register.and': '和',
    'register.privacyPolicy': '隐私政策',

    // Style Guide
    'styleGuide.backToLogin': '返回登录页面',
    'styleGuide.title': '班级萌宠园',
    'styleGuide.colorScheme': '配色方案',
    'styleGuide.primary': '青绿渐变',
    'styleGuide.primaryDesc': '主色 · 活力',
    'styleGuide.secondary': '薰衣草',
    'styleGuide.secondaryDesc': '辅助 · 梦幻',
    'styleGuide.accent': '珊瑚粉',
    'styleGuide.accentDesc': '强调 · 温暖',
    'styleGuide.success': '成功',
    'styleGuide.successDesc': '反馈 · 清新',
    'styleGuide.petColors': '宠物主题色',
    'styleGuide.typography': '字体系统',
    'styleGuide.cards': '卡片与阴影',
    'styleGuide.buttons': '按钮样式',
    'styleGuide.radius': '圆角系统',
    'styleGuide.leaderboard': '光荣榜',
    'styleGuide.leaderboardDesc': '累计总榜',
    'styleGuide.referenceStyle': '参考样式 - 清新活力的青绿渐变',

    // Home Page
    'home.defaultClass': '默认班级',
    'home.nav.store': '小卖部',
    'home.nav.interaction': '互动',
    'home.nav.leaderboard': '光荣榜',
    'home.nav.search': '搜索...',
    'home.nav.fullscreen': '全屏模式',
    'home.nav.undo': '撤回',
    'home.nav.more': '更多',
    'home.nav.settings': '设置',
    'home.nav.safeMode': '安全模式',
    'home.nav.safeModeActive': '点击退出',
    'home.emptyState.title': '暂无学生名单',
    'home.emptyState.description': '当前班级还没有添加学生，快去设置中添加吧',
    'home.emptyState.addStudents': '去设置添加学生',
    'home.search.noResults': '未找到学生',
    'home.search.noResultsDescription': '没有找到匹配"{query}"的学生',
    'home.search.clearSearch': '清除搜索',
    'home.safeMode.active': '安全模式已启用',
    'home.safeMode.description': '所有操作已被禁用，数据处于只读状态',
    'home.safeMode.exit': '退出安全模式',
    'home.safeMode.confirmTitle': '进入安全模式？',
    'home.safeMode.confirmMessage': '进入安全模式后，所有编辑操作都将被禁止，数据将处于只读状态。您可以随时退出安全模式。',
    'home.safeMode.confirm': '确认进入',

    // Class Modal
    'home.classModal.title': '新建班级',
    'home.classModal.manageClasses': '班级管理',
    'home.classModal.currentClass': '当前班级',
    'home.classModal.allClasses': '所有班级',
    'home.classModal.currentTag': '当前',
    'home.classModal.newClass': '新建班级',
    'home.classModal.className': '班级名称',
    'home.classModal.classNamePlaceholder': '请输入班级名称',
    'home.classModal.save': '保存',
    'home.classModal.cancel': '取消',
    'home.classModal.create': '创建',

    // Class Dropdown
    'home.classDropdown.students': '位学生',

    // Settings Page
    'settings.title': '设置',
    'settings.save': '保存设置',

    // Account Section
    'settings.account.title': '账号管理',
    'settings.account.expiryDate': '到期时间',
    'settings.account.renew': '续订',
    'settings.account.changePassword': '修改密码',
    'settings.account.logout': '退出登录',
    'settings.account.oldPassword': '旧密码',
    'settings.account.oldPasswordPlaceholder': '请输入旧密码',
    'settings.account.newPassword': '新密码',
    'settings.account.newPasswordPlaceholder': '请输入新密码（至少6位）',
    'settings.account.confirmNewPassword': '确认新密码',
    'settings.account.confirmPasswordPlaceholder': '请再次输入新密码',
    'settings.account.passwordRequired': '请填写所有密码字段',
    'settings.account.passwordMismatch': '新密码与确认密码不匹配',
    'settings.account.passwordTooShort': '密码长度至少6位',
    'settings.account.passwordChanged': '密码修改成功',
    'settings.account.logoutConfirm': '确认退出登录？',
    'settings.account.logoutMessage': '退出登录后，您需要重新登录才能继续使用。',

    // Sound Section
    'settings.sound.title': '设备音效',
    'settings.sound.description': '调整系统提示音的音量大小',
    'settings.sound.volume': '音量',
    'settings.sound.includes': '音效包含：喂食、扣分、升级、徽章、守护玩法、倒计时等提示音',

    // System Section
    'settings.system.title': '系统设置',
    'settings.system.systemName': '系统名称',
    'settings.system.systemNameHint': '修改后将应用到登录页面和所有班级',
    'settings.system.global': '全局',
    'settings.system.className': '当前班级名称',
    'settings.system.classNameHint': '仅修改当前选中班级的名称',
    'settings.system.interfaceTheme': '界面主题',
    'settings.system.interfaceThemeHint': '选择班级的主题配色方案',
    'settings.system.theme.springGreen': '春日绿',
    'settings.system.theme.oceanBlue': '海洋蓝',
    'settings.system.theme.sunsetOrange': '日落橙',
    'settings.system.theme.lavenderPurple': '薰衣紫',
    'settings.system.theme.rosePink': '玫瑰粉',

    // Pet Section
    'settings.pet.title': '宠物玩法设置',
    'settings.pet.description': '配置宠物养成相关的游戏规则和参数',
    'settings.pet.growthStages': '成长阶段配置',
    'settings.pet.growthStagesHint': '设置每个等级所需的累计食物数量（1级默认0，后续等级必须递增）',
    'settings.pet.level': '等级',
    'settings.pet.growthValidation': '注意：每个等级所需食物必须大于前一等级。1级固定为0食物。',
    'settings.pet.guardianSleep': '守护与睡眠设置',
    'settings.pet.guardianSleepHint': '这些设置只影响新保存的记录，不会改动已有数据',
    'settings.pet.useShield': '扣分先用护盾挡',
    'settings.pet.useShieldHint': '开启后，扣分会先被护盾抵消一部分，避免一次欠分',
    'settings.pet.maxShieldPerDay': '每天最多挡几分',
    'settings.pet.points': '分',
    'settings.pet.sleepEnabled': '几天没喂会睡着',
    'settings.pet.sleepEnabledHint': '连续完整教学日未喂养，下次课堂结算时宠物会睡着',
    'settings.pet.sleepDays': '连续未喂天数',
    'settings.pet.days': '天',
    'settings.pet.pauseRule': '暂停规则',
    'settings.pet.pauseRuleHint': '寒暑假、法定假期时手动暂停，避免长假导致睡着',
    'settings.pet.paused': '已暂停',
    'settings.pet.debtThreshold': '欠分阈值',
    'settings.pet.debtThresholdHint': '欠分达到设定值时，宠物会变成蛋形态',
    'settings.pet.debtThresholdValue': '欠分阈值',

    // Common Units
    'common.points': '分',
    'common.days': '天',

    // Points Section
    'settings.points.title': '加减分项目配置',
    'settings.points.description': '配置课堂表现的加分和扣分项目',
    'settings.points.addPoints': '加分区',
    'settings.points.deductPoints': '减分区',
    'settings.points.changeIcon': '更换图标',
    'settings.points.itemNamePlaceholder': '输入项目名称',
    'settings.points.add': '添加',
    'settings.points.editItem': '编辑项目',
    'settings.points.icon': '图标',
    'settings.points.itemName': '项目名称',
    'settings.points.pointValue': '分值',
    'settings.points.pointValueHint': '正数为加分，负数为扣分',
    'settings.points.selectIcon': '选择图标',
    'settings.points.iconPickerHint': '点击图标即可选择',
    'settings.points.iconCategory.academic': '学习',
    'settings.points.iconCategory.positive': '正面',
    'settings.points.iconCategory.gestures': '手势',
    'settings.points.iconCategory.faces': '表情',
    'settings.points.iconCategory.negative': '负面',
    'settings.points.iconCategory.warning': '警告',
    'settings.points.iconCategory.activities': '活动',
    'settings.points.iconCategory.nature': '自然',
    'settings.points.iconCategory.objects': '物品',
    'settings.points.iconCategory.symbols': '符号',

    // Students Section
    'settings.students.title': '学生名单',
    'settings.students.description': '管理当前班级的学生信息',
    'settings.students.namePlaceholder': '输入学生姓名',
    'settings.students.addSingle': '添加',
    'settings.students.addBatch': '批量添加',
    'settings.students.batchAddTitle': '批量添加学生',
    'settings.students.batchAddHint': '每行输入一个学生姓名，或直接从Excel粘贴',
    'settings.students.batchAddPlaceholder': '张小明\n李晓红\n王大伟',
    'settings.students.cancel': '取消',
    'settings.students.addAll': '添加全部',
    'settings.students.edit': '编辑',
    'settings.students.delete': '删除',
    'settings.students.empty': '暂无学生，请添加学生',
    'settings.students.petAssigned': '已分配',
    'settings.students.assignAllPets': '一键为所有学生分配宠物',

    // Groups Section
    'settings.groups.title': '分组管理',
    'settings.groups.description': '创建和管理学生分组',
    'settings.groups.manage': '管理分组',
    'settings.groups.members': '人',
    'settings.groups.newGroup': '新建分组',
    'settings.groups.randomGroup': '随机分组',
    'settings.groups.selectGroup': '勾选分组',
    'settings.groups.group': '小组',
    'settings.groups.groups': '组',
    'settings.groups.groupNamePlaceholder': '输入分组名称',
    'settings.groups.createGroup': '创建分组',
    'settings.groups.randomGroupHint': '选择要创建的分组数量，系统将随机分配学生',
    'settings.groups.selectGroupHint': '勾选要加入分组的学生',
    'settings.groups.currentGroups': '当前分组',
    'settings.groups.cancel': '取消',
    'settings.groups.save': '保存',

    // Pet Card
    'home.petCard.adopt': '领养',
    'home.petCard.level': '等级',
    'home.petCard.points': '积分',
    'home.petCard.pointsHistory': '积分记录',
    'home.petCard.needFood': '还需 {count} 个🍖',

    // Pet Selection
    'home.petSelection.title': '选择守护神兽',
    'home.petSelection.subtitle': '挑选一只专属守护神兽陪伴你的成长之旅',
    'home.petSelection.hint': '点击任意神兽即可领养',

    // Student Detail Page
    'studentDetail.back': '返回',
    'studentDetail.needFood': '还需 {count} 个🍖',
    'studentDetail.maxLevel': '满级',
    'studentDetail.shieldRemaining': '守护余量：{count} 分',

    // Common Units
    'common.points': '分',
    'common.days': '天',

    // Store
    'store.title': '小卖部',
    'store.storeTab': '商品',
    'store.manageTab': '管理',
    'store.historyTab': '兑换记录',
    'store.stock': '库存',
    'store.exchange': '兑换',
    'store.outOfStock': '已售罄',
    'store.addNewItem': '添加新商品',
    'store.itemIcon': '商品图标',
    'store.itemName': '商品名称',
    'store.itemNamePlaceholder': '输入商品名称',
    'store.badgesRequired': '所需徽章',
    'store.badges': '徽章',
    'store.addItem': '添加商品',
    'store.existingItems': '现有商品',
    'store.editItem': '编辑商品',
    'store.noHistory': '暂无兑换记录',
    'store.exchanged': '兑换了',
    'store.selectStudent': '选择学生',
    'store.noStudents': '暂无学生',
    'store.insufficient': '徽章不足',

    // Interaction
    'interaction.title': '互动工具',
    'interaction.randomPicker': '随机点名',
    'interaction.timer': '倒计时',
    'interaction.pickCount': '抽取人数',
    'interaction.clickToStart': '点击开始按钮抽取',
    'interaction.spinning': '抽取中...',
    'interaction.startSpin': '开始抽取',
    'interaction.noStudents': '没有可抽取的学生',
    'interaction.minutes': '分钟',
    'interaction.seconds': '秒',
    'interaction.min': '分钟',
    'interaction.pause': '暂停',
    'interaction.resume': '继续',
    'interaction.reset': '重置',
    'interaction.startTimer': '开始计时',

    // Leaderboard
    'leaderboard.title': '光荣榜',
    'leaderboard.individual': '个人榜',
    'leaderboard.group': '小组榜',
    'leaderboard.noData': '暂无数据',
    'leaderboard.noGroups': '暂无小组数据',
    'leaderboard.level': '等级',
    'leaderboard.points': '积分',
    'leaderboard.totalPoints': '总积分',
    'leaderboard.members': '人',

    // Level Up
    'levelUp.congratulations': '恭喜升级！',
    'levelUp.keepGoing': '继续加油，培养你的守护神兽',

    // Subscription
    'subscription.title': '选择订阅方案',
    'subscription.heading': '解锁全部功能',
    'subscription.subheading': '选择最适合您的方案，随时可以取消',
    'subscription.popular': '最受欢迎',
    'subscription.startTrial': '开始试用',
    'subscription.subscribe': '立即订阅',
    'subscription.guarantee': '30天无理由退款保证',
    'subscription.trial.name': '免费试用',
    'subscription.trial.duration': '7天试用',
    'subscription.trial.price': '¥0',
    'subscription.trial.feature1': '最多10名学生',
    'subscription.trial.feature2': '基础功能体验',
    'subscription.trial.feature3': '无需信用卡',
    'subscription.monthly.name': '月度订阅',
    'subscription.monthly.duration': '按月付费',
    'subscription.monthly.price': '¥29/月',
    'subscription.monthly.feature1': '无限学生数量',
    'subscription.monthly.feature2': '全部功能访问',
    'subscription.monthly.feature3': '数据云端同步',
    'subscription.monthly.feature4': '邮件技术支持',
    'subscription.quarterly.name': '季度订阅',
    'subscription.quarterly.duration': '按季度付费',
    'subscription.quarterly.price': '¥69/季',
    'subscription.quarterly.originalPrice': '¥87',
    'subscription.quarterly.feature1': '无限学生数量',
    'subscription.quarterly.feature2': '全部功能访问',
    'subscription.quarterly.feature3': '数据云端同步',
    'subscription.quarterly.feature4': '优先技术支持',
    'subscription.quarterly.feature5': '节省20%',
    'subscription.yearly.name': '年度订阅',
    'subscription.yearly.duration': '按年付费',
    'subscription.yearly.price': '¥199/年',
    'subscription.yearly.originalPrice': '¥348',
    'subscription.yearly.feature1': '无限学生数量',
    'subscription.yearly.feature2': '全部功能访问',
    'subscription.yearly.feature3': '数据云端同步',
    'subscription.yearly.feature4': '专属客服支持',
    'subscription.yearly.feature5': '节省43%',
  },
  en: {
    // App Name
    'app.name': 'Class Pet Garden',
    'app.slogan': 'Raise your pet by completing tasks',
    'app.footer': 'Class Pet Garden · Making Learning Fun',
    'app.description': 'Fresh & Vibrant Design · Apple Aesthetics',

    // Login Page
    'login.title': 'Login',
    'login.register': 'Register',
    'login.username': 'Username',
    'login.username.placeholder': 'Enter your username',
    'login.email': 'Email',
    'login.email.placeholder': 'Enter your email address',
    'login.password': 'Password',
    'login.password.placeholder': 'Enter your password',
    'login.confirmPassword': 'Confirm Password',
    'login.confirmPassword.placeholder': 'Re-enter your password',
    'login.forgotPassword': 'Forgot Password?',
    'login.submit': 'Login',
    'register.submit': 'Register',
    'register.terms': 'By registering, you agree to our',
    'register.termsOfService': 'Terms of Service',
    'register.and': 'and',
    'register.privacyPolicy': 'Privacy Policy',

    // Style Guide
    'styleGuide.backToLogin': 'Back to Login',
    'styleGuide.title': 'Class Pet Garden',
    'styleGuide.colorScheme': 'Color Scheme',
    'styleGuide.primary': 'Spring Green',
    'styleGuide.primaryDesc': 'Primary · Vibrant',
    'styleGuide.secondary': 'Lavender',
    'styleGuide.secondaryDesc': 'Secondary · Dreamy',
    'styleGuide.accent': 'Coral Pink',
    'styleGuide.accentDesc': 'Accent · Warm',
    'styleGuide.success': 'Success',
    'styleGuide.successDesc': 'Feedback · Fresh',
    'styleGuide.petColors': 'Pet Theme Colors',
    'styleGuide.typography': 'Typography',
    'styleGuide.cards': 'Cards & Shadows',
    'styleGuide.buttons': 'Buttons',
    'styleGuide.radius': 'Border Radius',
    'styleGuide.leaderboard': 'Leaderboard',
    'styleGuide.leaderboardDesc': 'Total Rankings',
    'styleGuide.referenceStyle': 'Reference - Fresh spring green gradient',

    // Home Page
    'home.defaultClass': 'Default Class',
    'home.nav.store': 'Store',
    'home.nav.interaction': 'Interaction',
    'home.nav.leaderboard': 'Leaderboard',
    'home.nav.search': 'Search...',
    'home.nav.fullscreen': 'Fullscreen',
    'home.nav.undo': 'Undo',
    'home.nav.more': 'More',
    'home.nav.settings': 'Settings',
    'home.nav.safeMode': 'Safe Mode',
    'home.nav.safeModeActive': 'Click to exit',
    'home.emptyState.title': 'No Students Yet',
    'home.emptyState.description': 'This class has no students added. Go to settings to add students.',
    'home.emptyState.addStudents': 'Add Students in Settings',
    'home.search.noResults': 'No Students Found',
    'home.search.noResultsDescription': 'No students matching "{query}"',
    'home.search.clearSearch': 'Clear Search',
    'home.safeMode.active': 'Safe Mode Enabled',
    'home.safeMode.description': 'All operations are disabled, data is read-only',
    'home.safeMode.exit': 'Exit Safe Mode',
    'home.safeMode.confirmTitle': 'Enter Safe Mode?',
    'home.safeMode.confirmMessage': 'In Safe Mode, all editing operations will be disabled and data will be read-only. You can exit Safe Mode at any time.',
    'home.safeMode.confirm': 'Confirm',

    // Class Modal
    'home.classModal.title': 'Create New Class',
    'home.classModal.manageClasses': 'Manage Classes',
    'home.classModal.currentClass': 'Current Class',
    'home.classModal.allClasses': 'All Classes',
    'home.classModal.currentTag': 'Current',
    'home.classModal.newClass': 'New Class',
    'home.classModal.className': 'Class Name',
    'home.classModal.classNamePlaceholder': 'Enter class name',
    'home.classModal.save': 'Save',
    'home.classModal.cancel': 'Cancel',
    'home.classModal.create': 'Create',

    // Class Dropdown
    'home.classDropdown.students': 'students',

    // Settings Page
    'settings.title': 'Settings',
    'settings.save': 'Save Settings',

    // Account Section
    'settings.account.title': 'Account Management',
    'settings.account.expiryDate': 'Expiry Date',
    'settings.account.renew': 'Renew',
    'settings.account.changePassword': 'Change Password',
    'settings.account.logout': 'Logout',
    'settings.account.oldPassword': 'Old Password',
    'settings.account.oldPasswordPlaceholder': 'Enter old password',
    'settings.account.newPassword': 'New Password',
    'settings.account.newPasswordPlaceholder': 'Enter new password (min. 6 characters)',
    'settings.account.confirmNewPassword': 'Confirm New Password',
    'settings.account.confirmPasswordPlaceholder': 'Re-enter new password',
    'settings.account.passwordRequired': 'Please fill in all password fields',
    'settings.account.passwordMismatch': 'New password and confirmation do not match',
    'settings.account.passwordTooShort': 'Password must be at least 6 characters',
    'settings.account.passwordChanged': 'Password changed successfully',
    'settings.account.logoutConfirm': 'Confirm Logout?',
    'settings.account.logoutMessage': 'After logging out, you will need to log in again to continue.',

    // Sound Section
    'settings.sound.title': 'Sound Effects',
    'settings.sound.description': 'Adjust the volume of system sound effects',
    'settings.sound.volume': 'Volume',
    'settings.sound.includes': 'Includes: feeding, deduction, level up, badge, guardian gameplay, countdown and other sound effects',

    // System Section
    'settings.system.title': 'System Settings',
    'settings.system.systemName': 'System Name',
    'settings.system.systemNameHint': 'Changes will apply to login page and all classes',
    'settings.system.global': 'Global',
    'settings.system.className': 'Current Class Name',
    'settings.system.classNameHint': 'Only changes the name of the currently selected class',
    'settings.system.interfaceTheme': 'Interface Theme',
    'settings.system.interfaceThemeHint': 'Select the color scheme for your class',
    'settings.system.theme.springGreen': 'Spring Green',
    'settings.system.theme.oceanBlue': 'Ocean Blue',
    'settings.system.theme.sunsetOrange': 'Sunset Orange',
    'settings.system.theme.lavenderPurple': 'Lavender Purple',
    'settings.system.theme.rosePink': 'Rose Pink',

    // Pet Section
    'settings.pet.title': 'Pet Gameplay Settings',
    'settings.pet.description': 'Configure game rules and parameters for pet raising',
    'settings.pet.growthStages': 'Growth Stage Configuration',
    'settings.pet.growthStagesHint': 'Set cumulative food required for each level (Level 1 defaults to 0, subsequent levels must increase)',
    'settings.pet.level': 'Level',
    'settings.pet.growthValidation': 'Note: Each level must require more food than the previous level. Level 1 is fixed at 0 food.',
    'settings.pet.guardianSleep': 'Guardian & Sleep Settings',
    'settings.pet.guardianSleepHint': 'These settings only affect new records, not existing data',
    'settings.pet.useShield': 'Shield Blocks Deductions First',
    'settings.pet.useShieldHint': 'When enabled, deductions are partially blocked by shield to prevent immediate debt',
    'settings.pet.maxShieldPerDay': 'Max Shield Per Day',
    'settings.pet.points': 'pts',
    'settings.pet.sleepEnabled': 'Sleep After Days Without Feeding',
    'settings.pet.sleepEnabledHint': 'Pet sleeps at next settlement if not fed for consecutive full school days',
    'settings.pet.sleepDays': 'Consecutive Days',
    'settings.pet.days': 'days',
    'settings.pet.pauseRule': 'Pause Rule',
    'settings.pet.pauseRuleHint': 'Manually pause during holidays to prevent sleep during long breaks',
    'settings.pet.paused': 'Paused',
    'settings.pet.debtThreshold': 'Debt Threshold',
    'settings.pet.debtThresholdHint': 'Pet turns into egg when debt reaches threshold',
    'settings.pet.debtThresholdValue': 'Debt Threshold',

    // Common Units
    'common.points': 'pts',
    'common.days': 'days',

    // Points Section
    'settings.points.title': 'Point System Configuration',
    'settings.points.description': 'Configure point rewards and deductions for class performance',
    'settings.points.addPoints': 'Rewards',
    'settings.points.deductPoints': 'Deductions',
    'settings.points.changeIcon': 'Change Icon',
    'settings.points.itemNamePlaceholder': 'Enter item name',
    'settings.points.add': 'Add',
    'settings.points.editItem': 'Edit Item',
    'settings.points.icon': 'Icon',
    'settings.points.itemName': 'Item Name',
    'settings.points.pointValue': 'Point Value',
    'settings.points.pointValueHint': 'Positive for rewards, negative for deductions',
    'settings.points.selectIcon': 'Select Icon',
    'settings.points.iconPickerHint': 'Click an icon to select',
    'settings.points.iconCategory.academic': 'Academic',
    'settings.points.iconCategory.positive': 'Positive',
    'settings.points.iconCategory.gestures': 'Gestures',
    'settings.points.iconCategory.faces': 'Faces',
    'settings.points.iconCategory.negative': 'Negative',
    'settings.points.iconCategory.warning': 'Warning',
    'settings.points.iconCategory.activities': 'Activities',
    'settings.points.iconCategory.nature': 'Nature',
    'settings.points.iconCategory.objects': 'Objects',
    'settings.points.iconCategory.symbols': 'Symbols',

    // Students Section
    'settings.students.title': 'Student List',
    'settings.students.description': 'Manage students in the current class',
    'settings.students.namePlaceholder': 'Enter student name',
    'settings.students.addSingle': 'Add',
    'settings.students.addBatch': 'Batch Add',
    'settings.students.batchAddTitle': 'Batch Add Students',
    'settings.students.batchAddHint': 'Enter one student name per line, or paste from Excel',
    'settings.students.batchAddPlaceholder': 'John Smith\nJane Doe\nBob Wilson',
    'settings.students.cancel': 'Cancel',
    'settings.students.addAll': 'Add All',
    'settings.students.edit': 'Edit',
    'settings.students.delete': 'Delete',
    'settings.students.empty': 'No students yet, please add students',
    'settings.students.petAssigned': 'Assigned',
    'settings.students.assignAllPets': 'Assign Pets to All Students',

    // Groups Section
    'settings.groups.title': 'Group Management',
    'settings.groups.description': 'Create and manage student groups',
    'settings.groups.manage': 'Manage Groups',
    'settings.groups.members': 'members',
    'settings.groups.newGroup': 'New Group',
    'settings.groups.randomGroup': 'Random Group',
    'settings.groups.selectGroup': 'Select Group',
    'settings.groups.group': 'Group',
    'settings.groups.groups': 'groups',
    'settings.groups.groupNamePlaceholder': 'Enter group name',
    'settings.groups.createGroup': 'Create Group',
    'settings.groups.randomGroupHint': 'Select the number of groups to create, students will be randomly assigned',
    'settings.groups.selectGroupHint': 'Select students to add to the group',
    'settings.groups.currentGroups': 'Current Groups',
    'settings.groups.cancel': 'Cancel',
    'settings.groups.save': 'Save',

    // Pet Card
    'home.petCard.adopt': 'Adopt',
    'home.petCard.level': 'Level',
    'home.petCard.points': 'Points',
    'home.petCard.pointsHistory': 'Points History',
    'home.petCard.needFood': 'Need {count} more 🍖',

    // Pet Selection
    'home.petSelection.title': 'Choose Your Guardian Beast',
    'home.petSelection.subtitle': 'Select a guardian companion for your journey',
    'home.petSelection.hint': 'Click any beast to adopt',

    // Student Detail Page
    'studentDetail.back': 'Back',
    'studentDetail.needFood': 'Need {count} more 🍖',
    'studentDetail.maxLevel': 'Max Level',
    'studentDetail.shieldRemaining': 'Shield: {count} pts left',

    // Common Units
    'common.points': 'pts',
    'common.days': 'days',

    // Store
    'store.title': 'Store',
    'store.storeTab': 'Items',
    'store.manageTab': 'Manage',
    'store.historyTab': 'History',
    'store.stock': 'Stock',
    'store.exchange': 'Exchange',
    'store.outOfStock': 'Out of Stock',
    'store.addNewItem': 'Add New Item',
    'store.itemIcon': 'Item Icon',
    'store.itemName': 'Item Name',
    'store.itemNamePlaceholder': 'Enter item name',
    'store.badgesRequired': 'Badges Required',
    'store.badges': 'badges',
    'store.addItem': 'Add Item',
    'store.existingItems': 'Existing Items',
    'store.editItem': 'Edit Item',
    'store.noHistory': 'No exchange history',
    'store.exchanged': 'exchanged',
    'store.selectStudent': 'Select Student',
    'store.noStudents': 'No students available',
    'store.insufficient': 'Insufficient',

    // Interaction
    'interaction.title': 'Interaction Tools',
    'interaction.randomPicker': 'Random Picker',
    'interaction.timer': 'Timer',
    'interaction.pickCount': 'Pick Count',
    'interaction.clickToStart': 'Click start to pick',
    'interaction.spinning': 'Picking...',
    'interaction.startSpin': 'Start Picking',
    'interaction.noStudents': 'No students available',
    'interaction.minutes': 'Minutes',
    'interaction.seconds': 'Seconds',
    'interaction.min': 'min',
    'interaction.pause': 'Pause',
    'interaction.resume': 'Resume',
    'interaction.reset': 'Reset',
    'interaction.startTimer': 'Start Timer',

    // Leaderboard
    'leaderboard.title': 'Leaderboard',
    'leaderboard.individual': 'Individual',
    'leaderboard.group': 'Group',
    'leaderboard.noData': 'No data available',
    'leaderboard.noGroups': 'No group data available',
    'leaderboard.level': 'Level',
    'leaderboard.points': 'Points',
    'leaderboard.totalPoints': 'Total Points',
    'leaderboard.members': 'members',

    // Level Up
    'levelUp.congratulations': 'Congratulations!',
    'levelUp.keepGoing': 'Keep going and nurture your guardian beast',

    // Subscription
    'subscription.title': 'Choose Your Plan',
    'subscription.heading': 'Unlock All Features',
    'subscription.subheading': 'Choose the plan that works best for you. Cancel anytime.',
    'subscription.popular': 'Most Popular',
    'subscription.startTrial': 'Start Trial',
    'subscription.subscribe': 'Subscribe Now',
    'subscription.guarantee': '30-day money-back guarantee',
    'subscription.trial.name': 'Free Trial',
    'subscription.trial.duration': '7-day trial',
    'subscription.trial.price': '$0',
    'subscription.trial.feature1': 'Up to 10 students',
    'subscription.trial.feature2': 'Basic features',
    'subscription.trial.feature3': 'No credit card required',
    'subscription.monthly.name': 'Monthly',
    'subscription.monthly.duration': 'Billed monthly',
    'subscription.monthly.price': '$4.99/mo',
    'subscription.monthly.feature1': 'Unlimited students',
    'subscription.monthly.feature2': 'All features included',
    'subscription.monthly.feature3': 'Cloud sync',
    'subscription.monthly.feature4': 'Email support',
    'subscription.quarterly.name': 'Quarterly',
    'subscription.quarterly.duration': 'Billed quarterly',
    'subscription.quarterly.price': '$11.99/qtr',
    'subscription.quarterly.originalPrice': '$14.97',
    'subscription.quarterly.feature1': 'Unlimited students',
    'subscription.quarterly.feature2': 'All features included',
    'subscription.quarterly.feature3': 'Cloud sync',
    'subscription.quarterly.feature4': 'Priority support',
    'subscription.quarterly.feature5': 'Save 20%',
    'subscription.yearly.name': 'Yearly',
    'subscription.yearly.duration': 'Billed annually',
    'subscription.yearly.price': '$34.99/yr',
    'subscription.yearly.originalPrice': '$59.88',
    'subscription.yearly.feature1': 'Unlimited students',
    'subscription.yearly.feature2': 'All features included',
    'subscription.yearly.feature3': 'Cloud sync',
    'subscription.yearly.feature4': 'Dedicated support',
    'subscription.yearly.feature5': 'Save 43%',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('zh');

  const t = (key: string, params?: Record<string, any>): string => {
    let text = translations[language][key as keyof typeof translations['zh']] || key;

    // Replace parameters like {count}, {name}, etc.
    if (params) {
      Object.keys(params).forEach(param => {
        text = text.replace(`{${param}}`, String(params[param]));
      });
    }

    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
